Fixed Typescript issues, added gameType selection
Vithop/TicTacToe pull request #18
Opened 2023-01-31 01:10 UTC by Mathuran

Added a new start page to select what game play you want

![image](https://user-images.githubusercontent.com/16548812/215633234-b843f055-2845-46fc-b4aa-4211d8a445bd.png)

2023-01-31 09:13 UTC, Khufu-I requested changes
If possible could you split Typescript issues from the rest of the code changes?

2023-01-31 09:13 UTC, Khufu-I commented on src/lib/AIPlayer.ts
> +export function selectMove(game: Game, difficulty: DifficultyType = Difficulty.Medium): number | undefined {
`selectMove` should always return a move. If the game is over then the next line should assert and throw an exception.

2023-01-31 09:13 UTC, Khufu-I commented on src/lib/AIPlayer.ts
> +		if (move == undefined) break;
`move` should never be undefined this should be typed properly.

2023-01-31 09:13 UTC, Khufu-I commented on src/lib/Game.ts
> +export type GameType = typeof GameTypes[keyof typeof GameTypes]
`Game.ts` could be thought as the game engine for Tic Tac Toe and `page.svelte` as the game controller. The game engine doesn't actually care who executes the move whether it's a real player or the AI, all it does is manage the game state according to the rules.
There shouldn't be any changes required to this file to support game type selection. See #16 for an example how the AI and Game engine were integrated on the Kotlin side.

2023-01-31 09:13 UTC, Khufu-I commented on src/lib/Game.ts
> +	}
Should not be necessary

2023-01-31 09:13 UTC, Khufu-I commented on src/routes/TicTacToe/+page.svelte
> +	import { selectMove as aiPlayerSelectMove } from '../../lib/AIPlayer';
You can import as AIPlayer and then call `AIPlayer.selectMove`

```suggestion
	import AIPlayer  from '../../lib/AIPlayer';
```

2023-01-31 16:28 UTC, Vithop requested changes
address siyamans concerns

2023-01-31 23:58 UTC, Mathuran commented on src/lib/AIPlayer.ts
> +		const rating = alphabeta(nextGame, isMaximizingPlayerX, lowerDifficulty(depth), newAlpha, newBeta);
would changing the name to ``lowerSearchDepth()``  be better

2023-02-01 00:07 UTC, Mathuran commented on src/lib/AIPlayer.ts
> +
yea the AI worked.

2023-02-01 01:00 UTC, Khufu-I commented on src/lib/AIPlayer.ts
> +
I don’t think you can beat the easy AI with this change. Now  that testing is enabled I can add tests for all this.

2023-02-01 01:04 UTC, Khufu-I commented on src/lib/AIPlayer.ts
> +		const rating = alphabeta(nextGame, isMaximizingPlayerX, lowerDifficulty(depth), newAlpha, newBeta);
Sure, you only need to decrease by one every iteration. I don’t understand what `lowerDifficulty` is trying to do. The existing code is doing a [depth first search](https://en.m.wikipedia.org/wiki/Depth-first_search)

2023-02-01 18:49 UTC, Mathuran commented on src/lib/AIPlayer.ts
> +		const rating = alphabeta(nextGame, isMaximizingPlayerX, lowerDifficulty(depth), newAlpha, newBeta);
Oh okay. I didn't understand what the code was doing either cause you were using the wrong types. I should just use a new var with the type Integer, not Difficulty which starts at the difficulty level selected.

2023-02-01 19:14 UTC, Khufu-I commented on src/lib/AIPlayer.ts
> +		const rating = alphabeta(nextGame, isMaximizingPlayerX, lowerDifficulty(depth), newAlpha, newBeta);
The number in the Difficulty enum is supposed to represent the depth it’s searching the game tree. This should probably be documented better. The [Kotlin code](https://github.com/Vithop/TicTacToe/blob/master/android/app/src/main/java/com/vithop/tictactoe/AIPlayer.kt#L77) is probably easier to understand. I made a mistake and `depth: DifficultyType` should be `depth: number`

@Vithop didn’t setup the Typescript properly and it’s not being checked correctly, so it’s their fault

2023-02-02 05:43 UTC, closed without merging