Tictactoe websocket server
Vithop/TicTacToe pull request #36
Opened 2023-02-24 21:04 UTC by Mathuran

Created a server that can handle online 2 player tic tac toe

2023-03-24 05:19 UTC, Vithop commented on oak/src/OnlineTicTacToe/ConnectedGames.ts
> +  connectPlayer2ToGame(gameName: GameName, socket: WebSocket) {
this name isn't very readable with "2To" maybe use "connectPlayersTogether" or "joinGame"

2023-03-24 05:33 UTC, Vithop commented on oak/src/OnlineTicTacToe/MessageHandler.ts
> +    switch (data.event) {
A switch case with no default case is bad

2023-03-24 05:33 UTC, Vithop commented on oak/src/OnlineTicTacToe/MessageHandler.ts
> +    player1?.send(stringGameDataEvent)
why are we optional chaining this? If player is null here we would need it to throw an error

2023-03-24 05:33 UTC, Vithop commented on oak/src/OnlineTicTacToe/ConnectedGames.ts
> +export class ConnectedGames extends Map<GameName, OnlineGame> {
Why do we need this class?

2023-03-24 05:33 UTC, Vithop commented on oak/src/OnlineTicTacToe/Middleware.ts
> +  try {
Why do we need a try catch? Can't we just check the map for game Name and close the socket if it fails. Try catch should be used if you don't know what error might come.

2023-03-27 22:05 UTC, Mathuran commented
> Why do we need this class? 

It's a wrapper for the GameName to OnlineGame Map. The class is good cause it follow LSP. It is needed to add game related functionality to the map.

2023-03-27 22:07 UTC, Mathuran commented on oak/src/OnlineTicTacToe/ConnectedGames.ts
> +export class ConnectedGames extends Map<GameName, OnlineGame> {
The class is a wrapper for the GameName to OnlineGame map. It encapsulates the functionality for managing a game while still being a map.

2023-03-27 22:27 UTC, Mathuran commented on oak/src/OnlineTicTacToe/MessageHandler.ts
> +    switch (data.event) {
yea I'll use if's instead

```suggestion
    if (data.event == GameEvents.updateGame) {
```

2023-03-27 22:49 UTC, Mathuran commented on oak/src/OnlineTicTacToe/MessageHandler.ts
> +    player1?.send(stringGameDataEvent)
True its was unnessary for player 1 but player 2 still requires it as it will only be defined after player 1 is. Therefore the player2 type is websocket | undefined.

2023-03-28 16:46 UTC, Vithop commented on oak/src/OnlineTicTacToe/Middleware.ts
> +  try {
You should provide methods to help resolve each type of error. This try catch seems like lazy writing to me.

2023-03-29 19:35 UTC, Mathuran commented on oak/src/OnlineTicTacToe/Middleware.ts
> +  try {
What do you mean this is lazy code? If any error is thrown here. Either from reading the request or trying to get the game then I want to close the socket and tell the client that the game doesn't exist. Which is what I wrote.

2023-04-18 22:14 UTC, Vithop requested changes

2023-04-18 22:14 UTC, Vithop commented on oak/src/OnlineTicTacToe/OnlineGame.ts
> +  player2: WebSocket | undefined
Why should this be allowed to be undefined. If it is undefined the online game object should not be made.

2023-04-18 22:14 UTC, Vithop commented on oak/src/OnlineTicTacToe/OnlineGame.ts
> +  boardState: string[]
This type is wrong

2023-04-18 22:14 UTC, Vithop commented on oak/src/OnlineTicTacToe/OnlineGame.ts
> +  joinedGame: "joined-game",
Having game everywhere in this enum seems repetitive

2023-04-18 22:14 UTC, Vithop commented on oak/src/server.ts
> +app.use(helloWorld)
Why do we still need hello world

2023-04-19 04:29 UTC, Vithop approved these changes

2023-04-19 04:29 UTC, merged