updating status to be an enum class instead of a sealed class
Vithop/TicTacToe pull request #37
Opened 2023-03-31 01:20 UTC by Mathuran

2023-03-31 07:35 UTC, Khufu-I requested changes

2023-03-31 07:35 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Bitboard.kt
> +  fun getData() = data
Why is data being exposed? This is an implementation detail and potentially the type could change based on performance needs.

2023-03-31 07:35 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Status.kt
> -  override fun toString() = when (this) {
Wonder what the game status says after this is removed?

2023-03-31 07:35 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Status.kt
> +    val xWon = { winPos: Bitboard -> XWon.apply { this.winPositions = winPos } }
Maybe function syntax is cleaner?
```suggestion
    fun XWon(winPositions: Bitboard) = XWon.apply{ this.winPositions = winPositions }
```

2023-03-31 07:35 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Status.kt
> +  fun getWinPosition(): Bitboard {
Can this just be a getter on the variable? Kotlin usually doesn't have getX functions.

2023-03-31 07:35 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Game.kt
> +      if (oWinPositions != null) return Status.oWon(oWinPositions)
If you keep the same constructor names you may not have to change these.

2023-03-31 16:53 UTC, Mathuran commented on android/app/src/main/java/com/vithop/tictactoe/Bitboard.kt
> +  fun getData() = data
I was debating whether to use casting or exposing data. What do you prefer?

2023-03-31 16:56 UTC, Mathuran commented on android/app/src/main/java/com/vithop/tictactoe/Status.kt
> -  override fun toString() = when (this) {
it would be how the state names are written currently. So "XTurn, OTurn, XWon...".

2023-04-01 07:07 UTC, Khufu-I approved these changes
Very nice, thanks for simplifying the Status enum and making all classes trivially serializable.

2023-04-01 07:07 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Status.kt
> +  fun getWinPosition(): Bitboard {
You mean [public getter private setter](https://stackoverflow.com/questions/33428957/kotlin-public-get-private-set-var) doesn't work in Kotlin?

2023-04-01 07:07 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Game.kt
> +      if (oWinPositions != null) return Status.oWon(oWinPositions)
I was thinking more like a constructor, so not a normal function.

2023-04-01 07:07 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Status.kt
> +    isWinState()
Please inline, this is like a contract for the function.
```suggestion
   check(this == XWon || this == OWon) { "winPositions is only valid for status XWon or OWon, status: $this" }
```

2023-04-01 07:07 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Status.kt
> +  fun isWinState() = check(this == XWon || this == OWon) { "Invalid status: $this" }
I don't think this re-usable.
```suggestion
```

2023-04-02 16:54 UTC, merged