Fix broken Status enum
Vithop/TicTacToe pull request #38
Opened 2023-04-04 06:48 UTC by Khufu-I

Member variables in enum classes are shared across all instances of that enum. For example multiple instances of `Status.XWon` would share the same `winPositions`. This diff simplifies the Status enum and moves the winPositions into the Game class. Unfortunately this causes duplicate computation but it improves correctness.

2023-04-04 16:12 UTC, Mathuran requested changes

2023-04-04 16:12 UTC, Mathuran commented on android/app/src/main/java/com/vithop/tictactoe/Game.kt
> +      val xWinPositions = winPositionsFor(Player.X)
Can we set `winPositions` in this section? That way you don't have to compute it separately. You can then remove the getter logic.

2023-04-06 05:34 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Game.kt
> +      val xWinPositions = winPositionsFor(Player.X)
I was thinking about this and had some trouble coming up with a good solution. So `winPositions` is a computed variable similar to `status`. If `winPositions` is memoized in `status` then it somehow also needs to be cached in the constructor. Otherwise you could create a new Tic tac toe game and end up with incorrect `winPositions` because `status` was not called.

2023-04-12 17:28 UTC, Mathuran commented on android/app/src/main/java/com/vithop/tictactoe/Game.kt
> +      val xWinPositions = winPositionsFor(Player.X)
Then maybe the constructor should only allow creating a new game of a new board. Another option would be to initialize the state and `winPosition` when the constructor initializes.

2023-04-12 18:25 UTC, Mathuran approved these changes

2023-04-15 19:09 UTC, Khufu-I commented on android/app/src/main/java/com/vithop/tictactoe/Game.kt
> +      val xWinPositions = winPositionsFor(Player.X)
Only allowing the constructor to take a new game would prevent a lot of testing or make it much more difficult. Also it would block the AI from simulating different game scenarios.
I'll update the next diff to minimize calls to computed properties `status` and `winPositions` that should help reduce unnecessary calls

2023-04-15 19:10 UTC, merged