Added more tests for game and ai
Vithop/TicTacToe pull request #40
Opened 2023-04-18 06:02 UTC by Vithop

2023-04-20 07:29 UTC, Khufu-I requested changes

2023-04-20 07:29 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +export type TTTPiece = "X" | "O" | "";
In Kotlin we used the term `Player`. Ideally this is an optional enum and we don't need empty string.

2023-04-20 07:29 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +  private winMap = [
This could be a static variable outside of this class.

2023-04-20 07:29 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +    return this.#status >= Status.Draw;
This is dangerous, do we have tests for `isGameOver`

2023-04-20 07:29 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +    }, []);
I don't think this is correct. If the game is over before the board is full this returns the wrong results.

2023-04-20 07:29 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +    if (this.isGameOver || this.#board[i] != "") return this.#status;
Wonder if an exception should be thrown, that's what we're doing in Kotlin.

2023-04-20 07:29 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +  private isWinPattern(winPattern: number[]): boolean {
Why does this have to be member function. Free functions are often more desirable.

2023-04-20 07:29 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +  private get isBoardFull(): boolean {
Why does this have to be member function. Free functions are often more desirable.

2023-04-20 07:29 UTC, Khufu-I commented on svelte/src/routes/TicTacToe/+page.svelte
> +    {#each game.board as toe, i}
👍🏾

2023-04-20 07:29 UTC, Khufu-I commented on svelte/tests/lib/ai-player.spec.ts
> +  let tttGame: Game;
No need for a shared `Game` object just create it within each test block

2023-04-20 07:29 UTC, Khufu-I commented on svelte/tests/lib/ai-player.spec.ts
> +  it("should select the best move on Hard", () => {
Good idea, we need similar tests for different difficulty levels on the Kotlin side.

2023-04-20 07:29 UTC, Khufu-I commented on svelte/tests/lib/game.spec.ts
> +  let ticTacToeGame: Game;
It's better to localize this variable, it allows your tests to run in parallel.

2023-04-20 07:29 UTC, Khufu-I commented on svelte/tests/lib/game.spec.ts
> +import { beforeEach, describe, expect, it } from "vitest";
I wonder if we should just use AI to generate tests from the AI code? If we use the same data types then this should be possible.

2023-04-21 06:45 UTC, Vithop commented on svelte/src/lib/Game.ts
> +export type TTTPiece = "X" | "O" | "";
This is used for rendering purposes but I guess `"X" | "O" | undefined` would also work for both rendering and player

2023-04-21 06:45 UTC, Vithop commented on svelte/src/lib/Game.ts
> +export type TTTPiece = "X" | "O" | "";
for typescript union type is better than enums

2023-04-21 06:45 UTC, Vithop commented on svelte/src/lib/Game.ts
> +  private winMap = [
but i want it scoped into the game

2023-04-21 06:45 UTC, Vithop commented on svelte/src/lib/Game.ts
> +    }, []);
tru then can we write this without branching?

2023-04-21 06:45 UTC, Vithop commented on svelte/src/lib/Game.ts
> +    if (this.isGameOver || this.#board[i] != "") return this.#status;
Then we would need error handling. I'm thinking of making it more of a state machine which is more robust

2023-04-21 06:45 UTC, Vithop commented on svelte/src/lib/Game.ts
> +  private get isBoardFull(): boolean {
i didn't know free funcs are desirable... explain?

2023-04-21 06:45 UTC, Vithop commented on svelte/src/lib/Game.ts
> +  private isWinPattern(winPattern: number[]): boolean {
same as above

2023-04-21 06:45 UTC, Vithop commented on svelte/tests/lib/game.spec.ts
> +import { beforeEach, describe, expect, it } from "vitest";
let's do it

2023-04-21 06:45 UTC, Vithop commented on svelte/tests/lib/game.spec.ts
> +  let ticTacToeGame: Game;
oh tru but it's a lot of duplicate code

2023-04-21 07:43 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +export type TTTPiece = "X" | "O" | "";
The name should also be Player instead of `TTTPiece`

2023-04-21 16:44 UTC, Khufu-I requested changes

2023-04-21 16:44 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +  private get isBoardFull(): boolean {
The main thinking is that free functions would use the public interface of objects vs internal data hence [leading to better encapsulation](https://www.drdobbs.com/cpp/how-non-member-functions-improve-encapsu/184401197).

2023-04-21 16:44 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +  private isWinPattern(winPattern: number[]): boolean {
Great [CppCon talk by Klaus Iglberger](https://www.youtube.com/watch?v=WLDT1lDOsb4) worth watching about this.

2023-04-21 16:44 UTC, Khufu-I commented on svelte/tests/lib/game.spec.ts
> +  let ticTacToeGame: Game;
Tests are run many many times and creating a bit of duplicate code in order to enable parallelization is worth it.

2023-04-22 17:19 UTC, Vithop commented on svelte/src/lib/Game.ts
> +    return this.#status >= Status.Draw;
But it's fast. There's three less operations

2023-04-22 17:21 UTC, Vithop commented on svelte/src/lib/Game.ts
> +    return this.#status >= Status.Draw;
I also have tests cases for this but I could add more

2023-04-22 18:37 UTC, Vithop commented on svelte/src/lib/Game.ts
> +    if (this.isGameOver || this.#board[i] != "") return this.#status;
I guess that's true will make an error for this

2023-04-22 19:03 UTC, Vithop commented on svelte/src/lib/Game.ts
> +  private get isBoardFull(): boolean {
but this reads the board which is contained in the game?

2023-05-13 19:37 UTC, Khufu-I approved these changes

2023-05-13 19:37 UTC, Khufu-I commented on svelte/src/lib/Game.ts
> +          this.#board[i] ?? "nothing"
Why would it be nothing? You're checking `this.#board[i] !== undefined`

2023-05-13 19:37 UTC, Khufu-I commented on svelte/tests/lib/game.spec.ts
> +    ]);
I believe an empty array `[]` is filled with undefined by default

2023-05-14 00:09 UTC, merged